### ISSUE TITLE
Utiliser Node portable + gulp-cli portable

### ISSUE THREAD

**Issue by k33g** [frinyvonnick/electron-workshop#27]
# Nouvelle version:

@ebriand @frinyvonnick 
- ci-dessous, le mode opératoire que j'ai utilisé pour créer des versions portables
- si je copie une étape dans le sous-répertoire `workplace` et que je lance `npm start` cela semble fonctionner
- j'ai du un peu ruser pour le `gulp-cli`

je vais vous fournir un lien vers la version osx si vous pouvez tester pour voir:
- dezipper à la racine (il faut que vous ayez un répertoire `electron-workshop` dans votre Home)
- `cd electron-workshop`
- `. setupws.sh`
- `cd workspace`
- copier une étape dans `workspace/votre_etape`
- `cd /votre_etape`
- `npm start`

> Téléchargement par là: https://github.com/k33g/electron-workshop-gen/blob/master/README.md
# WorkSpace creation
## Setup NodeJS

```
mkdir electron-workshop
cd electron-workshop
```
- Download a node version (http://nodejs.org/dist/latest/) and unzip it in `electron-workshop`
  - eg, for OSX: http://nodejs.org/dist/latest/node-v6.8.1-darwin-x64.tar.gz
- REM: I use this version:`node-v6.8.1-darwin-x64.tar.gz`

**OSX version:**
- create a file `setupws-osx.sh` (for setup the workspace) with this content:

```
export NODE_HOME=~/electron-workshop/node-v6.8.1-darwin-x64 # of course update the path if needed
export PATH=$NODE_HOME/bin:$PATH
```
- make the file executable: `chmod +x setupws-osx.sh`
- check if "all is ok":

```
. setupws-osx.sh
node --version # if the setup is OK you'll get v6.8.1
```

_:warning: note the `dot` `space` notation ("when you set an environment variable inside a script, that change is effective only within the script", so this is a workaround)_

**Linux version:**
- create a file `setupws-linux.sh` (for setup the workspace) with this content:

```
export NODE_HOME=~/electron-workshop/node-v6.8.1-linux-x64 # of course update the path if needed
export PATH=$NODE_HOME/bin:$PATH
```
- make the file executable: `chmod +x setupws-linux.sh`
- check if "all is ok":

```
. setupws-linux.sh
node --version # if the setup is OK you'll get v6.8.1
```

_:warning: note the `dot` `space` notation ("when you set an environment variable inside a script, that change is effective only within the script", so this is a workaround)_

**Windows version:**
- create a file `setupws-win.cmd` (for setup the workspace) with this content:

```
set NODE_HOME=%USERPROFILE%\electron-workshop\node-v6.8.1-win-x64
set PATH=%PATH%;%NODE_HOME%;
```
- check if "all is ok":

```
setupws-win.cmd
node --version # if the setup is OK you'll get v6.8.1
```
## Setup Electron

> Goal: add electron "runtime" to the workspace

:warning: **prerequisites**: `. setupws-<OS>.sh` (for OSX or Linux else `setupws-win.cmd` for Windows) has been run, and you are in the `electron-workshop` directory
- create a new directory (to "shelter" electron assets/runtime and each steps of the workshop):

```
# inside electron-workshop
mkdir workshop
cd workshop
```
- create a file `package.json`:

```
{
  "name": "electron-workshop",
  "version": "0.1.0",
  "description": "Workshop Electron du Devfest Nantes 2016",
  "main": "src/main.js",
  "scripts": {
    "start": "gulp",
    "dev": "gulp --debug",
    "lint": "standard",
    "less": "gulp less",
    "test": "npm run lint",
    "build": "electron-packager . --out=dist --app-version=$npm_package_version --platform=win32 --arch=x64 --prune --asar --overwrite --all --ignore \"node_modules/\\.bin\""
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/frinyvonnick/electron-workshop.git"
  },
  "keywords": [
    "electron-app",
    "electron"
  ],
  "author": "Yvonnick Frin <yvonnick.frin@zenika.com>",
  "contributors": [
    "Eric Briand <eric.briand@zenika.com>",
    "Philippe Charrière <k33g@github.com>"
  ],
  "files": [
    "index.js",
    "index.html",
    "index.css"
  ],
  "dependencies": {
    "electron-debug": "1.0.0",
    "electron-json-storage": "^2.0.1",
    "jimp": "0.2.27",
    "glob": "7.0.5"
  },
  "devDependencies": {
    "devtron": "1.1.0",
    "electron": "1.4.2",
    "electron-connect": "0.6.0",
    "electron-packager": "8.0.0",
    "gulp": "3.9.1",
    "gulp-less": "3.1.0",
    "less": "2.7.1",
    "standard": "8.2.0"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/frinyvonnick/electron-workshop/issues"
  },
  "homepage": "https://github.com/frinyvonnick/electron-workshop#readme"
}

```
- type `npm install` to get the electron assets
### OSX version

Add these lines to `setupws.sh`:

```
export ELECTRON_HOME=~/electron-workshop/workshop/node_modules/electron/dist/Electron.app/Contents/MacOS/
export PATH=$ELECTRON_HOME:$PATH
```

:warning: **from now, don't forget to run `. setupws.sh` (with the `dot` :wink:) before working with your new electron projects.**

**Check if all is OK**:
- run `. setupws-osx.sh`
- run `electron` you'll get an electron window
### Linux version

Add these lines to `setupws-linux.sh`:

```
export ELECTRON_HOME=~/electron-workshop/workshop/node_modules/electron/dist
export PATH=$ELECTRON_HOME:$PATH
```

:warning: **from now, don't forget to run `. setupws-linux.sh` (with the `dot` :wink:) before working with your new electron projects.**

**Check if all is OK**:
- run `. setupws-linux.sh`
- run `electron` you'll get an electron window
### Windows version

Add this line to `setupws-win.cmd`:

```
set ELECTRON_HOME=%USERPROFILE%\electron-workshop\workshop\node_modules\electron\dist
```

And update the `PATH`

```
set ELECTRON_HOME=%USERPROFILE%\electron-workshop\workshop\node_modules\electron\dist
```

**Check if all is OK**:
- run `. setupws-win.cmd`
- run `electron` you'll get an electron window
### gulp-cli
- create in `electron-workshop` a new directory `global-dependencies`
- create a `package.json` file in the `/global-dependencies` directory:

```
{
  "name": "electron_assets",
  "devDependencies": {
    "gulp-cli": "^1.2.2"
  }
}
```
- run `npm install`

We'll install `gulp-cli` as a kind of "local-global" dependency

**OSX version:**
- at the root of the `electron-workshop` directory, create a `gulp` file with this content:

```
gulp.js
```
- change the rights of the file: `chmod +x gulp`
- update `setupws-osx.sh` with adding these lines:

```
# GULP
export GULP_HOME=~/electron-workshop
export PATH=$GULP_HOME:$PATH
# GULP CLI
export GULPCLI_HOME=~/electron-workshop/global-dependencies/node_modules/gulp-cli/bin
export PATH=$GULPCLI_HOME:$PATH
```
- run again `. setupws-osx.sh`

**Linux version:**
- at the root of the `electron-workshop` directory, create a `gulp` file with this content:

```
gulp.js
```
- change the rights of the file: `chmod +x gulp`
- update `setupws-linux.sh` with adding these lines:

```
# GULP
export GULP_HOME=~/electron-workshop
export PATH=$GULP_HOME:$PATH
# GULP CLI
export GULPCLI_HOME=~/electron-workshop/global-dependencies/node_modules/gulp-cli/bin
export PATH=$GULPCLI_HOME:$PATH
```
- run again `. setupws-linux.sh`

**Windows version:**
- at the root of the `electron-workshop` directory, create a `gulp.cmd` file with this content:

```
node %USERPROFILE%\electron-workshop\global-dependencies\node_modules\gulp-cli\bin\gulp.js
```
- update `setupws-win.cmd` with adding these lines:

```
set GULP_HOME=%USERPROFILE%\electron-workshop
set GULPCLI_HOME=%USERPROFILE%\electron-workshop\global-dependencies\node_modules\gulp-cli\bin
```
- and update the `PATH`:

```
set PATH=%PATH%;%NODE_HOME%;%ELECTRON_HOME%;%GULP_HOME%;%GULPCLI_HOME%
```
- run again `setupws-win.cmd`
## And now ...

You can do this:

```
cd workshop/etape-0N # the step has to be in /workshop
npm start
```

Enjoy ;)

**Comment by k33g** [comment]
le lien https://github.com/k33g/electron-workshop-gen/blob/master/README.md

**Comment by k33g** [comment]
### Tests avec Fedora

par contre, nous risquons d'avoir des problèmes sur les distributions linux
- je viens de tester sur Fedora:
  - au chargement d'Electron j'obtiens:

```
 error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory. 
```

Fix: `sudo dnf install libXScrnSaver`

![image](https://cloud.githubusercontent.com/assets/491848/19417371/5645d8fa-93ab-11e6-88bb-2d3b1adc49e3.png)

**Comment by k33g** [comment]
### Tests avec une install vierge d'OSX

![image](https://cloud.githubusercontent.com/assets/491848/19417427/222ac416-93ad-11e6-9fa3-a63248ad4f17.png)

**Comment by k33g** [comment]
### Tests avec une install vierge d'Ubuntu

![image](https://cloud.githubusercontent.com/assets/491848/19417456/d6c98e8e-93ad-11e6-9c31-f7fd75645686.png)

**Comment by k33g** [comment]
### Tests avec Windows (pas le courage de re installer windows)

la galerie d'images n'apparaît pas

![image](https://cloud.githubusercontent.com/assets/491848/19417500/00ad6a94-93af-11e6-9dfc-2355ff0c37ce.png)

**Comment by frinyvonnick** [comment]
Nice, merci Philippe ! Je vais investiguer windows pour mardi ;)

**Comment by k33g** [comment]
et donc pas besoin de tous copier dans chaque repertoire

**Comment by k33g** [comment]
@frinyvonnick 👍 sur windows

**Comment by k33g** [comment]
@frinyvonnick @ebriand je suis en train de modifier les script pour utiliser `PWD` (bonne idée @ebriand ), sous linux et osx nickel, sous Windows c'est la 💩 
...mais je trouverais ... enfin j'espère 🙀

**Comment by k33g** [comment]
😂  🍹 rahhh ça fonctionne
