### ISSUE TITLE
Logistique 

### ISSUE THREAD

**Issue by frinyvonnick** [frinyvonnick/electron-workshop#9]
- [ ] S'assurer d'avoir accès à une connexion WEB
- [ ] Se renseigner sur le nombre de participants potentiels
- [ ] Faire une clé USB avec les dépendances pour les trois OS principaux

**Comment by k33g** [comment]
@frinyvonnick @ebriand 

#### Plan de secours
- [ ] proposer les dépendances en download via partage de connexion (ou router wifi)
